### ISSUE TITLE
[Feature] 전체 엔티티 생성

### ISSUE THREAD

**Issue by Haewonny** [GoogleEyes-ewha/hearo-server#1]
### 🚀 Feature
> 전체 엔티티 생성

### ✅ Tasks
- [x] `user`, `user_setting` 엔티티 생성
- [x] `item`, `category`, `item_tts` 엔티티 생성
- [x] `review`, `review_tts` 엔티티 생성
- [x] `category` 엔티티 생성
- [x] `wish` 엔티티 생성
- [x] 전체 연관 관계 설정
