### ISSUE TITLE
[Feature] ERD 수정사항 반영

### ISSUE THREAD

**Issue by Haewonny** [GoogleEyes-ewha/hearo-server#10]
### 🚀 Feature
>  itemTts, reviewTts ERD 수정사항 반영

### ✅ Tasks
- [ ] itemTts에 음성 타입 추가
- [ ] reviewTts에 음성 타입 추가
- [ ] item - reviewTts 연관관계 설정
