### ISSUE TITLE
[Feature] 일반 회원가입, 로그인 구현

### ISSUE THREAD

**Issue by Haewonny** [GoogleEyes-ewha/hearo-server#3]
### 🚀 Feature
> JWT 기반 회원가입, 로그인 구현

### ✅ Tasks
1차
- [x] 엔티티명 `user` → `member` 변경
- [x] SecurityConfig 설정
- [x] JWT 인증•인가 구현
- [x] 공통 response 포맷 생성
- [x] 회원가입 API 구현
- [x] 로그인 API 구현

2차
- [x] 액세스 토큰 만료 확인
- [x] 회원가입 & 로그인 예외 처리
- [x] 아이디 중복 예외 처리

3차
- [x] 액세스 토큰 재발급 구현
