### ISSUE TITLE
[Feature] 사용자 맞춤 설정 구현

### ISSUE THREAD

**Issue by Haewonny** [GoogleEyes-ewha/hearo-server#6]
### 🚀 Feature
> 사용자 맞춤 설정 구현

### ✅ Tasks
- [x] 사용자 맞춤 설정 API
- [x] 사용자 맞춤 설정 조회 API
- [x] 사용자 맞춤 설정 수정 API
